application: helloworld
version: 1
runtime: php55
api_version: 1

handlers:
 - url: /
   static_files: www/index.html
   upload: www/index.html

 - url: /(.*)
   static_files: www/\1
   upload: www/(.*)
